FROM nginx
COPY ./dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf
# docker build -t unioj_vue .
# docker tag 07f56af74c0e registry.cn-beijing.aliyuncs.com/uyistcoj/unioj-vue:latest
# docker push registry.cn-beijing.aliyuncs.com/uyistcoj/unioj-vue:latest